### ISSUE TITLE
Why was Gar achievement removed?

### ISSUE THREAD

**Issue by lain-dono** [anime-plus/graph#1]
MALgraph for achievements. Without them, it makes no sense.

**Comment by gineika** [comment]
You should be a part of the club, if you want to know what is going on and why.

I will be rewriting the code.

Genre-based achievements will be renamed to "skills". Thresholds will be different for every genre (max level in yuri - ~19 titles, comedy - ~2144). Achievements like "Boku no Pico" will be renamed to "quests".

Gar is not a real genre (not a "skill") and the list is too big (and outdated) for a "quest". It takes at least 10 minutes to confirm and add one anime. And it would take at least 50 hours to update the list. For mahou shoujo I can use Wiki, AniDB, etc., because it is a real genre (not on MAL).

Of course, there are volunteers. Gar achievement (or 'quest") MAY return.
